name: Build Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Install dependencies
        run: yarn install
      - name: Run tests
        run: yarn test
      - name: Run build
        run: yarn build
